apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: gopal-cluster 
  region: us-east-2
managedNodeGroups:
- name: gdnode
  instanceType: t2.small
  desiredCapacity: 3
  ssh:
    publicKeyName: dockergopal
